apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: luggage-tracking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: luggage-frontend:latest
        imagePullPolicy: Never
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: tracking-config
              key: NEXT_PUBLIC_API_URL
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
